sudo: required

services:
  - docker

before_install:
  - docker build -t behnamebrahimi/docker-complex-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true behnamebrahimi/docker-complex-react-test npm run test

after_success:
  - docker build -t behnamebrahimi/docker-complex-nginx ./nginx
  - docker build -t behnamebrahimi/docker-complex-client ./client
  - docker build -t behnamebrahimi/docker-complex-server ./server
  - docker build -t behnamebrahimi/docker-complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push behnamebrahimi/docker-complex-nginx
  - docker push behnamebrahimi/docker-complex-client
  - docker push behnamebrahimi/docker-complex-server
  - docker push behnamebrahimi/docker-complex-worker

deploy:
  provider: elasticbeanstalk
  region: 'the-region-that-elasticbeanstalk-is-created'
  app: 'docker-complex'
  env: 'Docker-complex-env'
  bucket_name: 's3-bucket-for-this-elasticbeanstalk-in-this-region-that-is-automatically-generated'
  bucket_path: 'docker-complex'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
